name: language_learning_app
description: A modern language learning application with AI integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.6
  firebase_app_check: ^0.3.2+6
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.2.4
  http: ^1.1.0
  intl: ^0.20.2
  flutter_tts: ^4.2.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  just_audio: ^0.10.4
  dio: ^5.3.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  lottie: ^3.3.1
  flutter_animate: ^4.3.0
  crypto: ^3.0.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
